name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
      with:
        go-version: '>=1.21.1'
    - name: Build & Test
      run: |
        go build -v
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6
      with:
        args: release --snapshot --skip=publish --clean
    - name: Colored Output Test
      if: runner.os == 'Linux'
      shell: script -q -e -c "bash {0}"
      run: go build
